HyperNews Portal/task/hypernews/hypernews/urls.py
from django.contrib import admin
from django.urls import path

from django.conf import settings
from django.conf.urls.static import static

from news.views import MainPageView
from news.views import CreateNewsView
from news.views import NewsListView
from news.views import NewsView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('news/', NewsListView.as_view(), name="search-index"),
    path('news/<int:id>/', NewsView.as_view()),
    path('news/create/', CreateNewsView.as_view()),
    path('', MainPageView.as_view(), name="search-index"),
]

urlpatterns += static(settings.STATIC_URL)

HyperNews Portal/task/hypernews/news/models.py
from django.db import models

# Create your models here.

HyperNews Portal/task/hypernews/news/views.py
import datetime
import json
from datetime import datetime

from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views import View
from django.views.decorators.csrf import csrf_exempt

from django.conf import settings
from django import forms


class MainPageView(View):

    def get(self, request, *args, **kwargs):
        return redirect("/news/")


class NewsListView(View):

    def get(self, request, *args, **kwargs):
        data = []
        with open(settings.NEWS_JSON_PATH, 'r') as f:
            data = json.load(f)
            q = request.GET.get('q')
            for d in data:
                dd = d
                if q and q in d['title']:
                    ded = self.findnewsbylink(data, dd['link'])
                    ded['created'] = datetime.strptime(ded['created'], "%Y-%m-%d %H:%M:%S").date().strftime("%Y-%m-%d")
                    return render(request, 'index.html', {"searched": ded})

        with open(settings.NEWS_JSON_PATH, 'r') as f:
            data = json.load(f)

        data.sort(key=lambda date: datetime.strptime(date['created'], "%Y-%m-%d %H:%M:%S"), reverse=True)

        for d in data:
            d['created'] = datetime.strptime(d['created'], "%Y-%m-%d %H:%M:%S").date().strftime("%Y-%m-%d")

        return render(request, 'index.html', {"list": data})

    @staticmethod
    def findnewsbylink(array, id):
        for data in array:
            if data['link'] == id:
                return data


class NewsView(View):
    def get(self, request, id):
        data = []
        with open(settings.NEWS_JSON_PATH, 'r') as f:
            data = json.load(f)

        data = self.findnewsbylink(data, id)
        return render(request, 'index.html', {"content": data})

    @staticmethod
    def findnewsbylink(array, id):
        for data in array:
            if data['link'] == id:
                return data


class CreateNewsForm(forms.Form):
    title = forms.CharField(required=False)
    text = forms.CharField(required=False)


class CreateNewsView(View):
    @csrf_exempt
    def get(self, request):
        form = CreateNewsForm()
        return render(request, 'index.html', {"source": form})

    @csrf_exempt
    def post(self, request):
        data = []
        with open(settings.NEWS_JSON_PATH, 'r') as f:
            data = json.load(f)

            form = CreateNewsForm(request.POST)

            if request.method == "POST" and form.is_valid():
                data.append(
                    {
                        "created": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                        "title": form.cleaned_data['title'],
                        "text": form.cleaned_data['text'],
                        "link": data[-1]['link'] + 1
                    }
                )

        with open(settings.NEWS_JSON_PATH, "w") as f:
            json.dump(data, f)

        return redirect("/news/")

HyperNews Portal/task/hypernews/hypernews/templates/news/index.html
<!doctype html>
<html lang="en">
<head>
    <title>News</title>
    {% load static %}
                    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>
    {% if list  %}
                    <h3>Coming soon</h3>
                    <h2>Hyper news</h2>

                    <form method="GET" action="/news/?q={q}">
                        <input type="text" name="q" size="40" maxlength="256" value="News">
                        <button>Search</button>
                    </form>

                    <ul id="list">
                        {% regroup list by created as listbydate %}
                        {% for news in listbydate %}

                            <h4>{{ news.grouper }}</h4>
                            <ul>
                                <li>
                                    {% for item in news.list %}
                                        <a href="/news/{{  item.link }}/" >{{ item.title }}</a>
                                    {% endfor %}
                                </li>
                            </ul>
                        {% endfor %}
                    </ul>

                    <a href="/news/create/">create news</a>
    {% elif source %}
       <form action="/news/create/" method="POST" enctype="multipart/form-data">{% csrf_token %}
            <p>
                <input type="text" name="title" id="id_title" value="{{ title }}"/>
                <input type="text" name="text" id="id_text"  value="{{ text }}"/>
                <input type="submit" value="append" />
            </p>

                <a href="/news/">all news</a>
        </form>
    {% elif searched %}
            <td>
                <div id="searched">
                            <h4> {{ searched.title }} </h4>
                            <h4> {{ searched.created }}  </h4>
                            <h4> {{ searched.text }}  </h4>
                            <a href="/news/{{  searched.link }}/" >{{ searched.title }}</a>
                </div>
            </td>
            <a href="/news/">all news</a>
    {% elif content %}
            <td>
                <div id="content">
                            <h2> {{ content.title }} </h2>
                            <p> {{ content.created }}  </p>
                            <p> {{ content.text }}  </p>
                </div>
            </td>
            <a href="/news/">all news</a>
    {% else %}
        <h3>Coming soon</h3>
    {% endif %}
</body>
</html>

HyperNews Portal/task/hypernews/templates/news/index.html
<!doctype html>
<html lang="en">
<head>
    <title>News</title>
    {% load static %}
                    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>
    {% if list  %}
                    <h3>Coming soon</h3>
                    <h2>Hyper news</h2>

                    <form method="GET" action="/news/?q={q}">
                        <input type="text" name="q" size="40" maxlength="256" value="News">
                        <button>Search</button>
                    </form>

                    <ul id="list">
                        {% regroup list by created as listbydate %}
                        {% for news in listbydate %}

                            <h4>{{ news.grouper }}</h4>
                            <ul>
                                <li>
                                    {% for item in news.list %}
                                        <a href="/news/{{  item.link }}/" >{{ item.title }}</a>
                                    {% endfor %}
                                </li>
                            </ul>
                        {% endfor %}
                    </ul>

                    <a href="/news/create/">create news</a>
    {% elif source %}
       <form action="/news/create/" method="POST" enctype="multipart/form-data">{% csrf_token %}
            <p>
                <input type="text" name="title" id="id_title" value="{{ title }}"/>
                <input type="text" name="text" id="id_text"  value="{{ text }}"/>
                <input type="submit" value="append" />
            </p>

                <a href="/news/">all news</a>
        </form>
    {% elif searched %}
            <td>
                <div id="searched">
                            <h4> {{ searched.title }} </h4>
                            <h4> {{ searched.created }}  </h4>
                            <h4> {{ searched.text }}  </h4>
                            <a href="/news/{{  searched.link }}/" >{{ searched.title }}</a>
                </div>
            </td>
            <a href="/news/">all news</a>
    {% elif content %}
            <td>
                <div id="content">
                            <h2> {{ content.title }} </h2>
                            <p> {{ content.created }}  </p>
                            <p> {{ content.text }}  </p>
                </div>
            </td>
            <a href="/news/">all news</a>
    {% else %}
        <h3>Coming soon</h3>
    {% endif %}
</body>
</html>